name: CI-CD Pipeline
env:
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask-application-packages11"
  EB_APPLICATION_NAME : "MyFlask"
  EB_ENVIRONMENT_NAME : "MyFlask-env"
  DEPLOY_PACKAGE_NAME : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME     : "eu-central-1"
on:
  push:
    branches:
    - main
jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1

    - name : Create ZIP dep pack
      run  : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      
